version: '3.8'

services:
  backend:
    build: ./backend
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
    depends_on:
      - db
    environment:
      - DATABASE_URL=postgresql://starlife_user:starlife_pass@db/starlife_db

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
      - ./backend/database.sql:/docker-entrypoint-initdb.d/init.sql
    environment:
      - POSTGRES_DB=starlife_db
      - POSTGRES_USER=starlife_user
      - POSTGRES_PASSWORD=starlife_pass

volumes:
  postgres_data:
